language: python
python:
  - "2.7"

sudo: false

services:
  - mongodb

# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"
  - "curl -L  https://github.com/coreos/etcd/releases/download/v2.2.5/etcd-v2.2.5-linux-amd64.tar.gz -o etcd-linux-amd64.tar.gz"
  - "tar xzvf etcd-linux-amd64.tar.gz"
  - "./etcd-v2.2.5-linux-amd64/etcd &"

# commands to run tests and style check
script:
  - flake8 .
  - nosetests -A 'not s3 and not github' --with-coverage --cover-erase --cover-branches --cover-package=orchestrator

after_success:
  - coveralls

notifications:
  webhooks:
    - https://orchestrator.elb.us-west-1.th.melt.sh/external/hooks/travis
