language: python
python:
  - "2.7"
  - "3.4"

env:
  - GITHUB_HOOK_SECRET_HINT=40

before_install:
  - "sudo apt-get update"

# command to install dependencies
install:
  - "sudo apt-get install libyaml-dev"
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"
  - "curl -L  https://github.com/coreos/etcd/releases/download/v0.4.6/etcd-v0.4.6-linux-amd64.tar.gz -o etcd-v0.4.6-linux-amd64.tar.gz"
  - "tar xzvf etcd-v0.4.6-linux-amd64.tar.gz"
  - "./etcd-v0.4.6-linux-amd64/etcd &"

# commands to run tests and style check
script:
  - flake8 .
  - nosetests -a '!s3' --with-coverage --cover-erase --cover-branches --cover-package=orchestrator

after_success:
  - coveralls

notifications:
  webhooks:
    - secure: "ztzwk/BgGlB+InQnxTcZVu3EoKaTnSBsumbPOTI+CtJd+rJV4LqCqHc1GGZy2/j47cwSUZj6/SOEO/QcSUB/PIMMwiRAsl4/phsKIETUxzOIcENlHZ5NXaHGbJSSLKhlZ40PasYPoMNV17bP83wUNVffa3a0GojBkTqDZdYtmlE="